# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Luke Graves Realty
logo: "/assets/logos/lgLogo.gif"
email: f/mbjpqyrp
description: >- # this means to ignore newlines until "baseurl:"
  As an Austin Broker/Realtor for the last 16 years, I have an exceptional
  understanding of the area. Whether you are interested in the charm of a
  Crestview Mid-Century Modern, the nightlife of a downtown loft, the luxury of
  a lakefront estate, or the schools of the Northwest, I can help you find the
  perfect property.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lukegravesrealty.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: lukegraves

social:
  name: Luke Graves
  links:
    - https://www.facebook.com/Luke-Graves-Realty-121912334512587

social_links:
  facebook: https://www.facebook.com/Luke-Graves-Realty-121912334512587
  yelp: https://www.yelp.com/biz/luke-graves-realty-austin

navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Testimonials
    url: /testimonials
  - title: Contact
    url: /contact

navigation_footer:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Basic Search
    url: http://lukegravesrealty.idxco.com/idx/5284/basicSearch.php
  - title: Testimonials
    url: /testimonials
  - title: Contact
    url: /contact


# Build settings
remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
